project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false
  resources: "datos"

execute: 
  freeze: auto
  cache: true
  daemon: 3600
  warning: false
  message: false

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Prácticas de Bioestadística con R"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2025"
  output-file: "bioestadistica-practicas-r"
  image: img/logos/sticker-bioestadistica-r.png
  cover-image: img/logos/sticker-bioestadistica-r.png
  sharing: [linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-tipos-datos.qmd
    - 03-preprocesamiento-datos.qmd
    - 04-frecuencias-graficos.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    code-overflow: wrap
    code-link: true
    toc: false
 
  pdf:
    latex-engine: xelatex
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker-bioestadistica-r.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker-bioestadistica-r.png


